In [2]:
print("Hello")

Hello


In [24]:
import numpy as np

In [92]:
#1creating arry using np.array() for 1 D & 2 D array

In [28]:
arr1d=np.array([1,2,3,4])

In [40]:
print(arr1d)

[1 2 3 4]


In [42]:
arr1d

array([1, 2, 3, 4])

In [48]:
arr2d=np.array([[1,2,3,4,5] ,[6,7,8,9,10]])

In [50]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [94]:
#2create zeros,ones,empty,random create value between 0 & 1

In [60]:
zeroArr=np.zeros((2,3))
zeroArr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
oneArr=np.ones((3,3))
oneArr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
emptyArr=np.empty((2,4))
emptyArr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
randomArr=np.random.random((2,3))
randomArr

array([[0.83535463, 0.3005301 , 0.91345789],
       [0.53950265, 0.39293464, 0.35110982]])

In [96]:
#3using np.arange() create array with a range value

In [74]:
arange=np.arange(1,10,3)
arange

array([1, 4, 7])

In [98]:
#4using linspace create a array with evenly space value of specified range

In [78]:
linspace=np.linspace(20,50)
linspace

array([20.        , 20.6122449 , 21.2244898 , 21.83673469, 22.44897959,
       23.06122449, 23.67346939, 24.28571429, 24.89795918, 25.51020408,
       26.12244898, 26.73469388, 27.34693878, 27.95918367, 28.57142857,
       29.18367347, 29.79591837, 30.40816327, 31.02040816, 31.63265306,
       32.24489796, 32.85714286, 33.46938776, 34.08163265, 34.69387755,
       35.30612245, 35.91836735, 36.53061224, 37.14285714, 37.75510204,
       38.36734694, 38.97959184, 39.59183673, 40.20408163, 40.81632653,
       41.42857143, 42.04081633, 42.65306122, 43.26530612, 43.87755102,
       44.48979592, 45.10204082, 45.71428571, 46.32653061, 46.93877551,
       47.55102041, 48.16326531, 48.7755102 , 49.3877551 , 50.        ])

In [82]:
linspace=np.linspace(20,50,10)
linspace

array([20.        , 23.33333333, 26.66666667, 30.        , 33.33333333,
       36.66666667, 40.        , 43.33333333, 46.66666667, 50.        ])

In [84]:
linspace=np.linspace(20,50,2)
linspace

array([20., 50.])

In [100]:
#5usnig copy()

In [88]:
original=np.array([1,2,3,4,5,6])
original

array([1, 2, 3, 4, 5, 6])

In [90]:
copy=np.copy(original)
copy

array([1, 2, 3, 4, 5, 6])

In [106]:
#6 identity matrix if u pass a 3 single number then tis consider 3x3 matrix

In [104]:
identity=np.identity(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])