In [3]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5,6,7,8])

In [7]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr2d=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2d

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
empty=np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
random=np.random.random((4,4))
random

array([[0.09545211, 0.15440232, 0.04358243, 0.70877308],
       [0.41178949, 0.13244429, 0.16384939, 0.07052034],
       [0.16752603, 0.28186995, 0.63299686, 0.72054387],
       [0.20901814, 0.2372839 , 0.16233616, 0.86403463]])

In [19]:
arange=np.arange(0,20,4)
arange

array([ 0,  4,  8, 12, 16])

In [21]:
linspace=np.linspace(0,20,5)
linspace

array([ 0.,  5., 10., 15., 20.])

In [23]:
linspace1=np.linspace(0,20,10)
linspace1

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [25]:
identity=np.identity(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
print(arr1.shape)

(8,)


In [29]:
print(arr2d.shape)

(2, 5)


In [31]:
print(arr2d.ndim)

2


In [33]:
print(arr2d.size)


10


In [35]:
print(arr1.itemsize)

8


In [37]:
print(arr1.dtype)

int64


In [39]:
#some imoportant topin min max average random reshape

In [41]:
num=np.array([10,20,30,40,50,60,70,80,90,200])
min_val=np.min(num)
max_val =np.max(num)
print(min_val)
print(max_val)

10
200


In [43]:
avg=np.average(num)
print(avg)

65.0


In [45]:
re_shape=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,5,16,17,18,19,20])
reshape_arr=np.reshape(re_shape,(5, 4))
print(reshape_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14  5 16]
 [17 18 19 20]]


In [47]:
random_array=np.random.rand(3,3)
print(random_array)

[[0.89571464 0.93516644 0.76531567]
 [0.06254556 0.06796703 0.05224796]
 [0.54015958 0.68705937 0.18190009]]


In [49]:
random_array=np.random.randint(2,70)
print(random_array)

66


In [51]:
#reshaping numpy

In [53]:
arr_2d=np.array([[1,2,3,4,5],[1,2,3,4,5]])
flattened_array=np.ravel(arr_2d)
print(arr_2d)
print(flattened_array)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[1 2 3 4 5 1 2 3 4 5]


In [55]:
tanspose_arr=np.transpose(arr_2d)
print(tanspose_arr)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


In [57]:
#Indexing

In [87]:
a1=np.array([1,2,3,4,5,6,7,8,9,0,10,11,22,33,44])
print(a1[1]+a1[2])
print(a1[1:6])
print(a1[:-3])
print(a1[::-1])
print(a1[1:5:2])
print(a1[3:10:2])

5
[2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9  0 10 11]
[44 33 22 11 10  0  9  8  7  6  5  4  3  2  1]
[2 4]
[4 6 8 0]


In [69]:
#access 2D array

In [97]:
a2=np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,101],[1,2,3,4,5,6,7,8,9,10]])
print(a2)
print(a2[0,1])
print(a2[0,-1])
print(a2[0:3,1:3])
print(a2[0:2,1:4])

[[  1   2   3   4   5   6   7   8   9  10]
 [  1   2   3   4   5   6   7   8   9 101]
 [  1   2   3   4   5   6   7   8   9  10]]
2
10
[[2 3]
 [2 3]
 [2 3]]
[[2 3 4]
 [2 3 4]]


In [99]:
#Iteration

In [107]:
for x in a2:
    print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5   6   7   8   9 101]
[ 1  2  3  4  5  6  7  8  9 10]


In [105]:
for x in np.nditer(a2):
    print(x)

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
101
1
2
3
4
5
6
7
8
9
10


In [109]:
#Numpy Operation

In [111]:
#A Basic Operation

In [115]:
a3=np.array([1,2,3,4,5])
a4=np.array([10,22,23,14,45])
print("Addition",a3+a4)
print("Substraction",a3-a4)
print("Multiplication",a3*a4)
print(".Dot product",a3.dot(a4))
print("inplace multiplication",a3+a4)

Addition [11 24 26 18 50]
Substraction [ -9 -20 -20 -10 -40]
Multiplication [ 10  44  69  56 225]
.Dot product 404
inplace multiplication [11 24 26 18 50]


In [117]:
#Unary Operation

In [119]:
a3.min()

1

In [121]:
a4.max()

45

In [123]:
a3.sum()

15

In [125]:
a4.sum()

114

In [131]:
np.exp(a3)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [133]:
np.sqrt(a3)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [135]:
np.sqrt(a4)

array([3.16227766, 4.69041576, 4.79583152, 3.74165739, 6.70820393])

In [137]:
np.sin(a1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,  0.        ,
       -0.54402111, -0.99999021, -0.00885131,  0.99991186,  0.01770193])

In [141]:
print(np.mean(a2))

8.533333333333333


In [143]:
np.median(a4)

22.0

In [157]:
np.std(a2)

17.389140928240884

In [159]:
#splitting

In [169]:
split_a2=np.hsplit(a3,5)
print(split_a2)

[array([1]), array([2]), array([3]), array([4]), array([5])]


In [171]:
print(a3)

[1 2 3 4 5]


In [173]:
print(a4)

[10 22 23 14 45]


In [185]:
a5=np.arange(50)
a6=np.arange(40)

In [177]:
print(a5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [179]:
split_a5=np.hsplit(a5,5)
print(split_a5)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]), array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]


In [195]:
split_a6=np.hsplit(arr2d,3)
print(split_a6)

ValueError: array split does not result in an equal division

In [189]:
print(arr2d)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [199]:
sp=np.hsplit(arr2d,5)
print(sp)

[array([[1],
       [1]]), array([[2],
       [2]]), array([[3],
       [3]]), array([[4],
       [4]]), array([[5],
       [5]])]


In [201]:
sp1=np.vsplit(arr2d,2)
print(sp1)

[array([[1, 2, 3, 4, 5]]), array([[1, 2, 3, 4, 5]])]


In [203]:
#Fancy Indexing

In [209]:
c=np.arange(24).reshape(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [211]:
c[[2,3,5]]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [215]:
#indexing boolean array

In [217]:
print(a5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [221]:
boolean_mask=a5 %2==0
result=a5[boolean_mask]
print(result)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [223]:
number_copy=a5.copy()
number_copy[a5 %2 ==0]=0
print(number_copy)

[ 0  1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23
  0 25  0 27  0 29  0 31  0 33  0 35  0 37  0 39  0 41  0 43  0 45  0 47
  0 49]


In [225]:
#broadcasting

In [231]:
a=np.array([[1,2,3,4],[2,4,5,6],[10,11,12,13]])
b=np.array([2,4,6,8])
print("a",a)
print("b",b)

a [[ 1  2  3  4]
 [ 2  4  5  6]
 [10 11 12 13]]
b [2 4 6 8]


In [233]:
c=a+b
print("Addition",c)

Addition [[ 3  6  9 12]
 [ 4  8 11 14]
 [12 15 18 21]]
